# Generated by Django 5.1.7 on 2025-03-14 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funcionarios", "0002_funcionario_departamento_funcionario_empresa_and_more"),
        ("registro_hora_extra", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrohoraextra",
            name="funcionario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="funcionarios.funcionario",
            ),
        ),
    ]
