# Generated by Django 5.1.7 on 2025-03-14 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departamentos", "0001_initial"),
        ("empresas", "0001_initial"),
        ("funcionarios", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="funcionario",
            name="departamento",
            field=models.ManyToManyField(to="departamentos.departamento"),
        ),
        migrations.AddField(
            model_name="funcionario",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="empresas.empresa",
            ),
        ),
        migrations.AddField(
            model_name="funcionario",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
